# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
linemode     = "size"
show_hidden  = true
mouse_events = [ "click", "scroll", "drag" ]

[preview]
wrap       = "yes"
tab_size   = 4
max_width  = 1920
max_height = 1080

[opener]
edit = [
	{ run = "${EDITOR:-nvim} %s", desc = "$EDITOR", for = "unix", block = true },
	{ run = "${EDITOR:-nvim} %s", desc = "$EDITOR",      for = "windows", block = true },
	{ run = "code %s",            desc = "code",         for = "windows", orphan = true },
	{ run = "code -w %s",         desc = "code (block)", for = "windows", block = true },
]

[plugin]
prepend_fetchers = [
	{ url = "*",         run = "git",             group = "git" },
	{ url = "*/",        run = "git",             group = "git" },
	{ url = "local://*", run = "mime-ext.local",  prio = "high", group = "mime" },
	{ url = "remote://*",run = "mime-ext.remote", prio = "high", group = "mime" },
]
prepend_previewers = [
	{ url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
	{ url = "*.md",   run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
]

[input]
cursor_blink = true
