MY_ZSH_CONFIG="$HOME/.config/zsh"       # 配置文件路径

# 加载基础配置
for file in env options aliases functions hook plugins; do
    source "$MY_ZSH_CONFIG/$file.zsh"

    # 加载本机/locals 配置，如果文件存在
    local_file="$MY_ZSH_CONFIG/locals/$file.zsh"
    [[ -f "$local_file" ]] && source "$local_file"
done

# 加载补全
autoload -Uz compinit
compinit -C

unset MY_ZSH_CONFIG
