set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'omerxx/tmux-floax'

# 主题设置
set -g status-position top

set -g @tokyo-night-tmux_theme night
set -g @tokyo-night-tmux_transparent 1

# 主机名组件
set -g @tokyo-night-tmux_show_hostname 0

# Git 组件（禁用）
set -g @tokyo-night-tmux_show_wbg 0

# 电池设置
set -g @tokyo-night-tmux_show_battery_widget 1
set -g @tokyo-night-tmux_battery_low_threshold 21   # 低电量阈值

# 网络速度
set -g @tokyo-night-tmux_show_netspeed 1

# 音乐状态
set -g @tokyo-night-tmux_show_music 1

# 日期与时间（禁用）
set -g @tokyo-night-tmux_show_datetime 0

# 键位绑定
set -g @vim_navigator_mapping_left "C-Left C-h"
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-Up C-k"
set -g @vim_navigator_mapping_down "C-Down C-j"
set -g @vim_navigator_mapping_prev ""  # 移除 C-\

set -g @floax-bind 'F'

set -g @vim_navigator_pattern '(\S+/)?g?\.?(view|l?n?vim?x?|fzf|nvr)(diff)?(-wrapped)?'

run '~/.config/tmux/plugins/tpm/tpm'
